codecov:
  require_ci_to_pass: true
  max_report_age: false
coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: 5%
        threshold: 1%
        base: auto
ignore: []
component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doesn't have a status defined will have a project type one
        target: auto
  individual_components:
    - component_id: module_capture
      name: capture
      paths:
        - "foosball/capture/**"
    - component_id: module_display
      name: display
      paths:
        - "foosball/display/**"
    - component_id: module_pipe
      name: pipe
      paths:
        - "foosball/pipe/**"
    - component_id: module_tracking
      name: tracking
      paths:
        - "foosball/tracking/**"
    - component_id: module_foosball
      name: foosball  # this is a display name, and can be changed freely
      paths:
        - "foosball(?!/(pipe|capture|tracking|display))/.*"
